### PR TITLE
OP-6 implement the new rest api

### PR DESCRIPTION
**Pull request by mwithi**
First implementation of the approved REST API (OP-6)

**TODO**

- [x] resolve conflicts and run test in https://github.com/informatici/openhospital-core/pull/215, then merge
- [x] resolve conflicts in https://github.com/informatici/openhospital-gui/pull/211, then merge
- [ ] check **TODO** and **FIXME** comments
- [ ] use Lombok for getters and setters (before or after this merge)
- [ ] use Lombok for logging (before or after this merge)

### CODE REVIEW

**Comment by mwithi** [comment]
**TODO**

- [ ] test with conflicts solved in https://github.com/informatici/openhospital-core/pull/215
- [ ] use Lombok for getters and setters (also after merge is fine)
- [ ] use Lombok for logging (also after merge is fine)

**Comment by mwithi** [comment]
I've just resolved compilation errors on my local and so added some comments.
I was not able to figure out how the checks are failing (it seems not founding core test classes used by the api tests ones)

**Comment by emecas** [comment]
> I was not able to figure out how the checks are failing (it seems not founding core test classes used by the api tests ones)

@mwithi  This is a problem caused by the new adopted location for test classes in CORE, `src/test/java` folder, testing classes in CORE used by the helpers in API are not accessible anymore from API project because the mentioned relocation.

I have added a couple PRs, one in CORE and one in API, in order to fix that problem before than anything else, by adding testing code to the CORE maven artifact, and importing it as a API's dependency .

https://github.com/informatici/openhospital-core/pull/225

https://github.com/informatici/openhospital-api/pull/72

Then one the compilation problem is solved,  we could focus on passing the  2 tests failing and the test broken on API project after all recent changes on this branch


```
Results :

Failed tests:
  PatientControllerTest.when_post_patients_PatientBrowserManager_newPatient_returns_false_then_OHAPIException_BadRequest:175 Range for response status value 201 expected:<CLIENT_ERROR> but was:<SUCCESSFUL>
  PatientControllerTest.when_put_update_patient_with_valid_body_and_existent_code_then_OK:234 Status expected:<200> but was:<400>
Tests in error:
  OpenHospitalApiApplicationTests.contextLoads � IllegalState Failed to load App...

Tests run: 105, Failures: 2, Errors: 1, Skipped: 0
```

**Review by emecas — CHANGES_REQUESTED** [review]
https://github.com/informatici/openhospital-api/pull/68/files#issuecomment-703362058

**Comment by mwithi** [comment]
> https://github.com/informatici/openhospital-api/pull/68/files#issuecomment-703362058

I cannot see this comment

**Comment by mwithi** [comment]
Only me I have a problem with provided Lombok version (1.16.10)?
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.607 s
[INFO] Finished at: 2020-10-05T23:20:07+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project openhospital-api: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\IDE\apache-maven-3.6.3\bin\..
Java version: 11.0.4, vendor: Oracle Corporation, runtime: D:\IDE\Java\openjdk-11u-11.0.4_11
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

If I upgrade Lombok version to 1.18.12, it runs 105 tests then it fails (like in the checks):
```
Results :

Failed tests:
  PatientControllerTest.when_post_patients_PatientBrowserManager_newPatient_returns_false_then_OHAPIException_BadRequest:175 Range for response status value 201 expected:<CLIENT_ERROR> but was:<SUCCESSFUL>
  PatientControllerTest.when_put_update_patient_with_valid_body_and_existent_code_then_OK:234 Status expected:<200> but was:<400>
Tests in error:
  OpenHospitalApiApplicationTests.contextLoads » IllegalState Failed to load App...

Tests run: 105, Failures: 2, Errors: 1, Skipped: 0
```

**Comment by dbmalkovsky** [comment]
The failure in the latest CI build includes:

<pre>
2020-10-06T19:21:45.4305591Z Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.isf.shared.mapper.converter.BlobToByteArrayConverter] found for dependency [org.isf.shared.mapper.converter.BlobToByteArrayConverter]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2020-10-06T19:21:45.4311893Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
2020-10-06T19:21:45.4316552Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
2020-10-06T19:21:45.4320906Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
2020-10-06T19:21:45.4445998Z 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
2020-10-06T19:21:45.4448695Z 	... 67 more
</pre>

This can be fixed by adding the `@Component` annotation to the `org.isf.shared.mapper.converter.ByteArrayToBlobConverter` and `org.isf.shared.mapper.converter.BlobToByteArrayConverter` files.

After that there will be an issue with the validation beans which I fixed by changing in the Core repo in the pom.xml file:

    <dependency>
          <groupId>javax.validation</groupId>
          <artifactId>validation-api</artifactId>
          <version>2.0.1.Final</version>
    </dependency> 
to

     <dependency>
           <groupId>org.hibernate</groupId>
           <artifactId>hibernate-validator</artifactId>
           <version>6.1.6.Final</version>
     </dependency>

After that is done the next error will be something like:

<pre>
No property patIDCode found for type TherapyRow!
</pre>

This I believe has to do with the fact that in `TherapyRow` the variable isn't `patIDCode` but rather `patID`.   FWIW, this seems like a strange name as it really isn't a **code** but rather a **patient**.

<pre>
	@NotNull
	@ManyToOne
	@JoinColumn(name="THR_PAT_ID")
	Patient patID;
</pre>

This property I believe is being generated when looking at the repository method names (note the `patIDCode` after **findBy** for example:

<pre>
public interface TherapyIoOperationRepository extends JpaRepository<TherapyRow, Integer> {
    List<TherapyRow> findAllByOrderByPatIDCodeAscTherapyIDAsc();
    List<TherapyRow> findByPatIDCodeOrderByPatIDCodeAscTherapyIDAsc(Integer patient);
    @Modifying
    void deleteByPatIDCode(@Param("patient") Integer patient);
}
</pre>

**Comment by mwithi** [comment]
> This can be fixed by adding the `@Component` annotation to the `org.isf.shared.mapper.converter.ByteArrayToBlobConverter` and `org.isf.shared.mapper.converter.BlobToByteArrayConverter` files.

Oops, sorry, my bad, I was the one adding it 5 months ago and the one soppressing it with 
https://github.com/informatici/openhospital-api/commit/1f60d533c67ca4c42d6210bd8233757285811124#diff-ad2133cb2a347e9b71f69d490d8fcd7aL15

I'm going to restore it now! 😅
Thanks a lot!

**Comment by mwithi** [comment]
The maven build works, nevertheless some errors still remain for @Test contextLoad() when ran from within the IDE. 
Anyway this OP-6 has been open for too long and we need to merge it. 

Remainng tasks will be fixed with other issues:
- [ ] check **TODO** and **FIXME** comments
- [ ] use Lombok for getters and setters (before or after this merge)
- [ ] use Lombok for logging (before or after this merge)
- [ ] test contextLoad() fails if ran within Eclipse

**Pull request merged**
