### PR TITLE
Chore Remove dead store

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Found with SpotBugs

Remove creation of `admissionType` as it is not used in the test method.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
@emecas Can you please confirm as it appears that you are the original author?  Thanks

**Comment by dbmalkovsky** [comment]
Locally no tests failed but in the CI build 2 did fail:
````
Failed tests: 
  WardControllerTest.testNewWard_200:172 Range for response status value 400 expected:<SUCCESSFUL> but was:<CLIENT_ERROR>
  WardControllerTest.testUpdateWard_200:196 Range for response status value 400 expected:<SUCCESSFUL> but was:<CLIENT_ERROR>
````

Neither of those tests were the single test that I touched in this PR.   I think there have been some recent Ward changes in Core.

**Comment by dbmalkovsky** [comment]
@mwithi I believe your fix for the ward tests was incorrect.  Please review my changes to that produced a clean local run and a clean CI build.  Probably this should be committed so others don't see the same failures.

**Review by mwithi — APPROVED** [review]
@dbmalkovsky yes, I noticed that just after but had no time to fix! Thanks!

**Pull request merged**
