### PR TITLE
Chore Wrapper object can just be primitive type

### PR DESCRIPTION
**Pull request by dbmalkovsky**

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
This was found using IntelliJ's Analyze tool.  The inspection that found this is `Wrapper type may be primitive`.  The description says: Reports local variable of wrapper type which has most of its usages primitive.

In this case there was one report that had a mixture of uses: primitive and wrapper (specifically `Boolean`) that was left the way it was.

**Comment by dbmalkovsky** [comment]
@mwithi @emecas Any reason this hasn't been merged?  Is there something you'd like me to change?

**Review by emecas — COMMENTED** [review]
I'm experimentation compilation testing against develop branch of CORE (b5c2c5507), in Vaccine, Disease, and Ward modules

image

**Review by emecas — APPROVED** [review]
thanks @dbmalkovsky

**Pull request merged**
