### PR TITLE
Chore: narrow variable scope and/or move closer to actual use of variable

### PR DESCRIPTION
**Pull request by dbmalkovsky**

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by mwithi** [comment]
@dbmalkovsky could you please resolve conflicts? Thanks

**Comment by dbmalkovsky** [comment]
@mwithi I have resolved the diffs.

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
