### PR TITLE
OH2-396 | Add a lock mechanism in all the remaining entities without it

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-396

Paired with [#1432](https://github.com/informatici/openhospital-core/pull/1432)

### CODE REVIEW

**Comment by mwithi** [comment]
Hi @SilverD3, could you please investigate why this check is still failing?

https://github.com/informatici/openhospital-api/actions/runs/11294464648/job/31414961187?pr=479#step:15:24

Courious that apparently we have the same problem on OH2-400:

https://github.com/informatici/openhospital-api/actions/runs/11380232995/job/31659149868?pr=482

**Comment by SilverD3** [comment]
> Hi @SilverD3, could you please investigate why this check is still failing?

@mwithi checks are failing because the paired PRs in the CORE are not merged

**Comment by mwithi** [comment]
> @mwithi checks are failing because the paired PRs in the CORE are not merged

Failing check is related to the openapi oh.yaml generated from this new API

**Comment by mwithi** [comment]
> > @mwithi checks are failing because the paired PRs in the CORE are not merged

Anyway, trying to fix this on https://github.com/informatici/openhospital-api/pull/484, please have look at it!

**Pull request merged**
