### PR TITLE
OP-779 Remove useless code after removing fields ADM_OPE_ID_A, ADM_DATE_OP, ADM_RESOP

### PR DESCRIPTION
**Pull request by mwithi**
See OP-779.

Paired with https://github.com/informatici/openhospital-core/pull/864.

### CODE REVIEW

**Review by dbmalkovsky — CHANGES_REQUESTED** [review]
The tests here work because they are running against the old version of Admission.java; i.e. before the three fields were removed in `TestAdmission.java` in the Core project.  As a result all the tests in this repo in  'org.isf.admission.rest.AdmissionControllerTest` fail.

**Comment by mwithi** [comment]
> The tests here work because they are running against the old version of Admission.java; i.e. before the three fields were removed in `TestAdmission.java` in the Core project. As a result all the tests in this repo in 'org.isf.admission.rest.AdmissionControllerTest` fail.

They ran and still run fine on my local, on both Eclipse and Maven command line. Are you sure you are testing against any recent core? Changes in this PR cannot affect tests (Operation management is done outside the AdmissionController)

image

**Comment by dbmalkovsky** [comment]
Sorry, my bad.   Just too tired and too much work.  LGTM.

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Pull request merged**
