### PR TITLE
Chore: update to SpringBoot 3.2.5

### PR DESCRIPTION
**Pull request by dbmalkovsky**
This change matches changes in CORE.

Not sure about the intermediate commits; I tried resetting things but nothing seems to help.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
I have fixes pending for the compile failure FWIW.

**Comment by mwithi** [comment]
> I have fixes pending for the compile failure FWIW.

yes, please, fix compilation errors first

**Comment by dbmalkovsky** [comment]
Changes committed; compile is clean;

**Comment by mwithi** [comment]
I'm not sure why it keeps failing the OpenAPI check, let me investigate a bit

**Comment by mwithi** [comment]
> I'm not sure why it keeps failing the OpenAPI check, let me investigate a bit

Looks like the API application is no longer able to keep running without a DB connection, changes in #440 fix that

**Comment by mwithi** [comment]
> Looks like the API application is no longer able to keep running without a DB connection (hence the impossibilty to run the `mvn springdoc-openapi:generate` goal in openapi.yml), changes in #440 fix that, please check

Please could you try to apply same changes in #440 to this PR and see if it solves? Thanks

**Review by mwithi — APPROVED** [review]
With latests fixes all checks pass

**Pull request merged**
