### PR TITLE
Chore: remove redundant initializers 

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Also moved some variable definitions within the scope that they are used in and reformatted one method that was sorely out of shape.

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by mwithi** [comment]
Please @dbmalkovsky can you fix the conflicts?

**Comment by dbmalkovsky** [comment]
@mwithi I resolved the conflicts.

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
