### PR TITLE
OH2-415 | OH2-316 | Add endpoint to update age types

### PR DESCRIPTION
**Pull request by SilverD3**
See OH2-415, OH2-316.

Paired with https://github.com/informatici/openhospital-ui/pull/689

### CODE REVIEW

**Comment by SilverD3** [comment]
Breaking changes confirmed

**Comment by mwithi** [comment]
Also in this case I get this error (fixed)

**Comment by SilverD3** [comment]
> Also in this case I get this error:

I've noticed it. It's not related to this PR. I opened the issue OH2-416 to address it.

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
